"""steps

Revision ID: 4c2101a9ff2d
Revises: 0b070a225422
Create Date: 2020-08-03 17:32:31.028608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2101a9ff2d'
down_revision = '0b070a225422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('step1', sa.String(length=200), nullable=True),
    sa.Column('step2', sa.String(length=200), nullable=True),
    sa.Column('step3', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('steps')
    # ### end Alembic commands ###
