"""steps

Revision ID: cb999d465264
Revises: 4c2101a9ff2d
Create Date: 2020-08-04 00:26:37.748974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb999d465264'
down_revision = '4c2101a9ff2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('steps', 'step1',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=250),
               existing_nullable=True)
    op.alter_column('steps', 'step2',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=250),
               existing_nullable=True)
    op.alter_column('steps', 'step3',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=250),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('steps', 'step3',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('steps', 'step2',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('steps', 'step1',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###
